### ISSUE TITLE
Custom Palette not Pushed

### ISSUE THREAD

**Issue by Pamzirp** [looker-open-source/gzr#68]
When migrating Custom Palette in Looker is not pushed, the Palette was created in both instances. and it seems the content pushed is corrupted now as the Visual is blank but the Data is there

**Comment by drstrangelooker** [comment]
Custom palettes need to be handled separately. I'm going to add some additional code to handle this. This may happen in multiple phases.

1. Palettes can only be imported by admins. So Look or Dashboard imports by a non-admin user can't bring across the palette. If a palette does not exist on the target side, I will set the default palette instead. This will at least result in a working palette for the visualization, even if it is not optimal.
1. Palettes are represented by what appears to be a uuid that I doubt is consistent across instances. I'll add the palette name to the exports and try to match on name during import. If there is no match I'll warn and use the default palette.
1. What is the proper behavior when two systems have different default palettes? If a visualization is exported with `is_default_palette: true` and `palette_name: "foo"` but I import into a system with a default palette of "bar", should I choose the local default of use "foo"? I'm leaning toward respecting the local default but adding a warning and possibly and override switch. 
1. I'll add a new feature to export and import palettes. Admins will need to import a palette before importing the visualization. I'll add a warning.

**Comment by drstrangelooker** [comment]
This should work now. You will need to redo the exports before attempting an import.

**Comment by ra185170** [comment]
Hi @drstrangelooker ,
The issue is marked closed but I still see this issue on v0.2.41

Traceback (most recent call last):
        30: from C:/Ruby26-x64/bin/gzr:23:in `<main>'
        29: from C:/Ruby26-x64/bin/gzr:23:in `load'
        28: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/exe/gzr:36:in `<top (required)>'
        27: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/commands/look.rb:74:in `import'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/commands/look/import.rb:47:in `execute'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/modules/session.rb:207:in `with_session'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/commands/look/import.rb:51:in `block in execute'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/modules/filehelper.rb:88:in `read_file'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/commands/look/import.rb:52:in `block (2 levels) in execute'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/modules/look.rb:165:in `create_fetch_query'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:171:in `find_vis_config_reference'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/modules/look.rb:166:in `block in create_fetch_query'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:192:in `find_color_palette_reference'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:192:in `each'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:192:in `block in find_color_palette_reference'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:192:in `find_color_palette_reference'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:192:in `each'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:192:in `block in find_color_palette_reference'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:189:in `find_color_palette_reference'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/modules/look.rb:167:in `block (2 levels) in create_fetch_query'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:230:in `update_color_palette!'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.41/lib/gzr/command.rb:199:in `color_palette_lookup!': no implicit conversion of Symbol into Integer (TypeError)
